voting:
    id: SPb-1234567890
    location: г. Санкт-Петербург, ул. Будапештская, д. 1, корп. 1
    type: Заочная # форма голосования
    start: 20.06.2021
    end: 14.07.2021
    return-address: г. Санкт-Петербург, ул. Будапештская, д. 1, корп. 1, ящик для голосования, размещенный в каждой парадной многоквартирного дома
    agenda:
        - question: Выбор председателя общего собрания собственников помещений в многоквартирном доме.
          solution: Выбрать председателем общего собрания собственников помещений собственника кв. 383 - Иванова Ивана Ивановича
        - question: Выбор секретаря общего собрания собственников помещений в многоквартирном доме.
          solution: Выбрать секретарем общего собрания собственников помещений собственника кв. 93 - Сидорова Сидора Сидоровича
        - question: Утверждение состава счетной комиссии в количестве 2 человек.
          solution: Избрать счетную комиссию в составе 2 человек ...
        - question: asdf1
          solution: fdas1
        - question: asdf2
          solution: fdas2
        - question: asdf3
          solution: fdas3
        - question: Тест
          solution: тест
